min_version = "2025.12.5"

[settings]
pipx.uvx = true
npm.bun = true

[tools]
# Dependencies for mise
usage = "3.4.0"

# Common packages
bat = "0.26.1"
btop = "1.4.7"
fzf = "0.73.1"
jq = "1.8.1"
yq = "4.53.2"

# Python
uv = "0.11.19"
"pipx:yt-dlp" = "2026.3.17"

# Go packages
go = "1.26.4"
"go:github.com/charmbracelet/gum" = "0.17.0"
