name: Lint conventions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    name: Conventional Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - name: Install commitlint
        run: npm install -g commitlint@v21.0.2

      - name: Run commitlint
        run: commitlint --verbose --from ${{ github.event.pull_request.base.sha }} --to ${{ github.sha }}
