name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MISE_TASK_RUN_AUTO_INSTALL: "false"

jobs:
  dockerfiles:
    name: Dockerfiles
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.12
          install_args: hadolint

      - name: Run linter
        run: mise lint:dockerfiles

  markdown:
    name: Markdown
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.12
          install_args: node bun npm:markdownlint-cli2

      - name: Run linter
        run: mise lint:markdown

  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.12
          install_args: node bun npm:prettier

      - name: Run linter
        run: mise lint:prettier

  scripts:
    name: Scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.12
          install_args: shellcheck

      - name: Run linter
        run: mise lint:scripts
