name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MISE_TASK_RUN_AUTO_INSTALL: "false"

jobs:
  dockerfiles:
    name: Dockerfiles
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install lint tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install_args: hadolint

      - name: Run linter
        run: mise lint:dockerfiles

  markdown:
    name: Markdown
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install lint tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install_args: bun npm:markdownlint-cli2

      - name: Run linter
        run: mise lint:markdown

  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install lint tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install_args: bun npm:prettier

      - name: Run linter
        run: mise lint:prettier

  scripts:
    name: Scripts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install lint tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          install_args: shellcheck

      - name: Run linter
        run: mise lint:scripts
