name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  renovate:
    name: Renovate Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate Renovate config
        uses: docker://ghcr.io/renovatebot/renovate:43.233.4@sha256:6a173a90f5382bd60c46329ae7ee019107b69c6bdcd61829aa58eeb42202b35d
        with:
          args: renovate-config-validator renovate.json
