name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  renovate:
    name: Renovate Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate Renovate config
        uses: docker://ghcr.io/renovatebot/renovate:43.257.2@sha256:71f9c23d9bdb689cb5dc57180bf37cefca786ea42203002068802fbd17e39769
        with:
          args: renovate-config-validator renovate.json
